### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by Wpj-001** [kuruwa2/kyber-sca#1]
Hello, I am very interested in the code you provided, but I encountered an error "No such file or directory: './ELMO/output/traces/trace00001.trc'" when running the code. Could you please provide the energy trace file? Thank you!
![image](https://github.com/kuruwa2/kyber-sca/assets/164879804/f6a6fd3e-fd2d-41ab-80ff-47bc9fff7aad)

**Comment by kuruwa2** [comment]
Sorry, the files are in my old pc, so I can't upload it rn.
You can generate the trace files yourself by elmo using your own binaries, see https://github.com/sca-research/ELMO for more info.
